SELECT NAME, TEL, INSTR(TEL, ')',1 ,1) FROM STUDENT WHERE DEPTNO1 = 201;

SELECT NAME, TEL, SUBSTR(TEL, 1, INSTR(TEL, ')')-1) "AREA CODE" FROM STUDENT WHERE DEPTNO1 = 201;

SELECT ENAME, REPLACE(ENAME , SUBSTR(ENAME, 2, 2), '--') "REPLACE" FROM EMP WHERE DEPTNO = 20;

SELECT NAME, JUMIN, REPLACE(JUMIN, SUBSTR(JUMIN, 7), '-/-/-/-') "REPLACE" FROM STUDENT WHERE DEPTNO1 = 101;

SELECT NAME, TEL, REPLACE(TEL, SUBSTR(TEL, 5, 3), '***') "REPLACE" FROM STUDENT WHERE DEPTNO1 = 102;

SELECT NAME, TEL, REPLACE(TEL, SUBSTR(TEL, -4, 4), '****') "REPLACE" FROM STUDENT WHERE DEPTNO1 = 101;

INSERT INTO MEMO VALUES(MEMO_SEQ.NEXTVAL, '메모7', '뛰뛰빵', '빵님의 글', SYSDATE);

